services:  
  redis:
    image: redis:7.0.11-alpine
  django:
    container_name: django
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:  
      - 8000:8000
    environment:
      - DEBUG=0
      - SECRET_KEY=Pouria1389
      - ALLOWED_HOSTS=localhost,127.0.0.1,asiagadget.liara.run
      - MELLI_PAYAMAK_KEY=4b034bd6-9c2c-429e-a215-301a402a7ee5
    depends_on:
      - redis
  celery:
    container_name: celery1
    build:
      context: .
    command: celery --app=config worker -l INFO -Q queue1
    environment:
      - DEBUG=0
      - SECRET_KEY=Pouria1389
      - ALLOWED_HOSTS=localhost,127.0.0.1,asiagadget.liara.run
      - MELLI_PAYAMAK_KEY=4b034bd6-9c2c-429e-a215-301a402a7ee5
    depends_on:
      - redis
      - django