# Generated by Django 5.1.3 on 2024-12-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_options_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تولید کد تایید'),
        ),
    ]
