# Generated by Django 5.1.3 on 2025-02-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_otp_generated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='shipment_address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
    ]
