# Generated by Django 5.1.3 on 2025-01-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=50, verbose_name='نام فروشگاه')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='لوگوی وبسایت')),
                ('banner_1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='بنر شماره 1')),
                ('banner_2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='بنر شماره 2')),
                ('banner_3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='بنر شماره 3')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='شماره تلفن')),
                ('telegram_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس تلگرام')),
                ('instagram_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس اینستاگرام')),
                ('whatsapp_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس واتساپ')),
            ],
        ),
    ]
