# Generated by Django 5.1.3 on 2025-01-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websitesetting',
            options={'verbose_name': 'تنظیمات', 'verbose_name_plural': 'تنظیمات'},
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='banner_1',
            field=models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='بنر شماره 1'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='banner_2',
            field=models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='بنر شماره 2'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='banner_3',
            field=models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='بنر شماره 3'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='لوگوی وبسایت'),
        ),
    ]
