# Generated by Django 5.1.3 on 2025-04-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_websitesetting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetting',
            name='shop_address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس فروشگاه'),
        ),
    ]
