# Generated by Django 5.1.3 on 2025-01-30 18:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='نام و نام خانوادگی')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ سفارش')),
                ('total_price', models.PositiveBigIntegerField(verbose_name='قیمت کل')),
                ('shipping_address', models.TextField(verbose_name='آدرس حمل و نقل')),
                ('status', models.CharField(choices=[('pending', 'پردازش'), ('confirmed', 'ثبت شده'), ('shipped', 'پست شده'), ('cancelled', 'لغو شده')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='شناسه تراکنش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.AddField(
            model_name='cartitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.order', verbose_name='سفارش'),
        ),
    ]
