# Generated by Django 5.1.3 on 2025-12-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='کد ارجاع'),
        ),
    ]
