# Generated by Django 5.1.3 on 2024-11-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brand_color_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='title',
            field=models.CharField(default='a', max_length=255, verbose_name='نام'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='color',
            name='title',
            field=models.CharField(default='aaa', max_length=255, verbose_name='نام'),
            preserve_default=False,
        ),
    ]
