# Generated by Django 5.1.3 on 2025-01-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AddField(
            model_name='product',
            name='shipment_price',
            field=models.PositiveBigIntegerField(default=45000, verbose_name='هزینه پست'),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
