# Generated by Django 5.1.3 on 2024-11-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_brand_title_color_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_at'], 'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(default='default.png', upload_to='brands/', verbose_name='تصویر برند'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default.png', upload_to='categories/', verbose_name='تصویر دسته بندی'),
        ),
    ]
