# Generated by Django 5.1.3 on 2025-02-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.png', upload_to='products/', verbose_name='تصویر اصلی'),
        ),
    ]
