# Generated by Django 5.1.3 on 2025-04-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='portable',
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, choices=[('int', 'عدد'), ('box', 'جعبه'), ('dozen', 'جین')], max_length=5, null=True, verbose_name='واحد'),
        ),
    ]
