# Generated by Django 5.1.3 on 2025-04-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_portable_product_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('int', 'عدد'), ('box', 'جعبه'), ('dozen', 'جین')], default='int', max_length=5, verbose_name='واحد'),
        ),
    ]
